name: Run Survival PvP Weapon Bots

on:
  workflow_dispatch:

jobs:
  run-bots:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm ci || npm i
      - name: Start bots
        env:
          SERVER_HOST: ${{ secrets.MC_HOST }}
          SERVER_PORT: ${{ secrets.MC_PORT }}
          AUTH_MODE:   ${{ secrets.MC_AUTH }}
        run: node bot.js
        
